//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseTracker.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpenseDefinitionOfstringint", Namespace="http://schemas.datacontract.org/2004/07/ExpenseTrackingService")]
    [System.SerializableAttribute()]
    public partial class ExpenseDefinitionOfstringint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Income", Namespace="http://schemas.datacontract.org/2004/07/ExpenseTrackingService")]
    [System.SerializableAttribute()]
    public partial class Income : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Expense", Namespace="http://schemas.datacontract.org/2004/07/ExpenseTrackingService")]
    [System.SerializableAttribute()]
    public partial class Expense : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IExpenseTrackerServiceOf_String_Int32")]
    public interface IExpenseTrackerServiceOf_String_Int32 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Add_Income", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Add_IncomeResponse")]
        void Add_Income(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Add_Income", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Add_IncomeResponse")]
        System.Threading.Tasks.Task Add_IncomeAsync(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Add_Expense", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Add_ExpenseResponse")]
        void Add_Expense(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Add_Expense", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Add_ExpenseResponse")]
        System.Threading.Tasks.Task Add_ExpenseAsync(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Update_Income", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Update_IncomeResponse")]
        void Update_Income(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Update_Income", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Update_IncomeResponse")]
        System.Threading.Tasks.Task Update_IncomeAsync(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Update_Expense", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Update_ExpenseResponse")]
        void Update_Expense(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Update_Expense", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Update_ExpenseResponse")]
        System.Threading.Tasks.Task Update_ExpenseAsync(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Delete_Income", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Delete_IncomeResponse")]
        void Delete_Income(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Delete_Income", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Delete_IncomeResponse")]
        System.Threading.Tasks.Task Delete_IncomeAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Delete_Expense", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Delete_ExpenseResponse")]
        void Delete_Expense(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Delete_Expense", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Delete_ExpenseResponse")]
        System.Threading.Tasks.Task Delete_ExpenseAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_Income", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_IncomeResponse")]
        ExpenseTracker.ServiceReference1.Income[] Get_Income();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_Income", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_IncomeResponse")]
        System.Threading.Tasks.Task<ExpenseTracker.ServiceReference1.Income[]> Get_IncomeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_Expense", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_ExpenseResponse")]
        ExpenseTracker.ServiceReference1.Expense[] Get_Expense();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_Expense", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_ExpenseResponse")]
        System.Threading.Tasks.Task<ExpenseTracker.ServiceReference1.Expense[]> Get_ExpenseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_Income_By_Id", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_Income_By_IdResponse" +
            "")]
        ExpenseTracker.ServiceReference1.Income Get_Income_By_Id(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_Income_By_Id", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_Income_By_IdResponse" +
            "")]
        System.Threading.Tasks.Task<ExpenseTracker.ServiceReference1.Income> Get_Income_By_IdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_Expense_By_Id", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_Expense_By_IdRespons" +
            "e")]
        ExpenseTracker.ServiceReference1.Expense Get_Expense_By_Id(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_Expense_By_Id", ReplyAction="http://tempuri.org/IExpenseTrackerServiceOf_String_Int32/Get_Expense_By_IdRespons" +
            "e")]
        System.Threading.Tasks.Task<ExpenseTracker.ServiceReference1.Expense> Get_Expense_By_IdAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExpenseTrackerServiceOf_String_Int32Channel : ExpenseTracker.ServiceReference1.IExpenseTrackerServiceOf_String_Int32, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExpenseTrackerServiceOf_String_Int32Client : System.ServiceModel.ClientBase<ExpenseTracker.ServiceReference1.IExpenseTrackerServiceOf_String_Int32>, ExpenseTracker.ServiceReference1.IExpenseTrackerServiceOf_String_Int32 {
        
        public ExpenseTrackerServiceOf_String_Int32Client() {
        }
        
        public ExpenseTrackerServiceOf_String_Int32Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpenseTrackerServiceOf_String_Int32Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpenseTrackerServiceOf_String_Int32Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpenseTrackerServiceOf_String_Int32Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add_Income(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object) {
            base.Channel.Add_Income(Object);
        }
        
        public System.Threading.Tasks.Task Add_IncomeAsync(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object) {
            return base.Channel.Add_IncomeAsync(Object);
        }
        
        public void Add_Expense(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object) {
            base.Channel.Add_Expense(Object);
        }
        
        public System.Threading.Tasks.Task Add_ExpenseAsync(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object) {
            return base.Channel.Add_ExpenseAsync(Object);
        }
        
        public void Update_Income(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object) {
            base.Channel.Update_Income(Object);
        }
        
        public System.Threading.Tasks.Task Update_IncomeAsync(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object) {
            return base.Channel.Update_IncomeAsync(Object);
        }
        
        public void Update_Expense(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object) {
            base.Channel.Update_Expense(Object);
        }
        
        public System.Threading.Tasks.Task Update_ExpenseAsync(ExpenseTracker.ServiceReference1.ExpenseDefinitionOfstringint Object) {
            return base.Channel.Update_ExpenseAsync(Object);
        }
        
        public void Delete_Income(int Id) {
            base.Channel.Delete_Income(Id);
        }
        
        public System.Threading.Tasks.Task Delete_IncomeAsync(int Id) {
            return base.Channel.Delete_IncomeAsync(Id);
        }
        
        public void Delete_Expense(int Id) {
            base.Channel.Delete_Expense(Id);
        }
        
        public System.Threading.Tasks.Task Delete_ExpenseAsync(int Id) {
            return base.Channel.Delete_ExpenseAsync(Id);
        }
        
        public ExpenseTracker.ServiceReference1.Income[] Get_Income() {
            return base.Channel.Get_Income();
        }
        
        public System.Threading.Tasks.Task<ExpenseTracker.ServiceReference1.Income[]> Get_IncomeAsync() {
            return base.Channel.Get_IncomeAsync();
        }
        
        public ExpenseTracker.ServiceReference1.Expense[] Get_Expense() {
            return base.Channel.Get_Expense();
        }
        
        public System.Threading.Tasks.Task<ExpenseTracker.ServiceReference1.Expense[]> Get_ExpenseAsync() {
            return base.Channel.Get_ExpenseAsync();
        }
        
        public ExpenseTracker.ServiceReference1.Income Get_Income_By_Id(int Id) {
            return base.Channel.Get_Income_By_Id(Id);
        }
        
        public System.Threading.Tasks.Task<ExpenseTracker.ServiceReference1.Income> Get_Income_By_IdAsync(int Id) {
            return base.Channel.Get_Income_By_IdAsync(Id);
        }
        
        public ExpenseTracker.ServiceReference1.Expense Get_Expense_By_Id(int Id) {
            return base.Channel.Get_Expense_By_Id(Id);
        }
        
        public System.Threading.Tasks.Task<ExpenseTracker.ServiceReference1.Expense> Get_Expense_By_IdAsync(int Id) {
            return base.Channel.Get_Expense_By_IdAsync(Id);
        }
    }
}
